### ISSUE TITLE
Make the collection dependent on the redhat_csp_download collection once it's available on middleware_automation

### ISSUE THREAD

**Issue by gzaronikas** [web-servers/jws-ansible-playbook#29]
@gzaronikas one note: we need to make the collection dependent on the redhat_csp_download one, to ensure this dep is pulled automatically when installing the jws collection. I'll add that as soon as we have migrate and properly release redhat_csp_download under the middleware_automation umbrella.

_Originally posted by @rpelisse in https://github.com/web-servers/jws-ansible-playbook/issues/20#issuecomment-872939166_

**Comment by rpelisse** [comment]
@gzaronikas That's fixed :)

```
# ansible-galaxy collection install middleware_automation-jws-0.0.1.tar.gz 
Process install dependency map
Starting collection install process
Installing 'middleware_automation.jws:0.0.1' to '/root/.ansible/collections/ansible_collections/middleware_automation/jws'
Installing 'middleware_automation.redhat_csp_download:1.1.1' to '/root/.ansible/collections/ansible_collections/middleware_automation/redhat_csp_download'

```

**Comment by gzaronikas** [comment]
Thanks to PR #33  that issue can now be closed :) Cheers @rpelisse
